language: android
dist: trusty
before_install:
  - "chmod +x gradlew"
  - yes | sdkmanager "platforms;android-30"
android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.2
    - android-30
    - build-tools-30.0.2
    - extra
    - sys-img-x86-android-30
