sudo: false
language: android
dist: trusty
before_install:
  - "chmod +x gradlew"
  - yes | sdkmanager "platforms;android-30"
before_script:
  - echo no | android create avd --force -n test -t android-26 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.2
    - android-30
    - android-26
    - addon-google_apis-google-30
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - extra
    - sys-img-x86-android-26
    - sys-img-armeabi-v7a-android-26
